import Head from 'next/head'
import Image from 'next/image'
import style from "../styles/pages/home/Home.module.scss"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome to Next js master</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Herr+Von+Muellerhoff&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&family=Aguafina+Script&family=Poppins:wght@300;400;500;600;700&family=Oswald:wght@300;400;700&display=swap"
          rel="stylesheet"></link>
      </Head>

      <main className={style.test}>Homepage</main>
    </div>
  );
}
