import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css';
import style from "../styles/pages/home/Home.module.scss"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome to Next js master</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.test}>
        Homepage
      </main>

    </div>
  )
}
